package handler

import (
	"encoding/json"
	"testing"
	"time"

	"github.com/candrasyahputra/radius-server/internal/model"
)

func TestNewCustomerDetailResponseShapesPayload(t *testing.T) {
	customPrice := int64(210000)
	packageID := "pkg-1"
	routerID := "router-1"
	odpPortID := "odp-1"
	acsURL := "http://acs.local:7547"
	uptime := int64(1234)
	rxPower := -18.5
	txPower := 2.1
	invoicePaidAmount := int64(210000)
	paymentMethod := "bank_transfer"
	modelName := "ZL-2113X"
	vendorName := "HWTC"
	startedAt := time.Date(2026, 5, 5, 17, 1, 38, 0, time.UTC)
	joinDate := time.Date(2026, 5, 1, 0, 0, 0, 0, time.UTC)
	dueDate := time.Date(2026, 5, 24, 0, 0, 0, 0, time.UTC)
	provisionedAt := time.Date(2026, 5, 1, 15, 56, 0, 0, time.UTC)

	resp := newCustomerDetailResponse(&model.Customer{
		ID:               "cust-1",
		TenantID:         "tenant-1",
		CustomerCode:     "260501001",
		Name:             "TAWARIKH",
		NIK:              "1204241705840001",
		Phone:            "081377187725",
		Email:            "",
		Address:          "",
		PackageID:        &packageID,
		RouterID:         &routerID,
		ODPPortID:        &odpPortID,
		ConnectionType:   "pppoe",
		PPPoEUsername:    "2605017725",
		PPPoEPassword:    "47461371",
		IPAddress:        "10.10.10.10",
		JoinDate:         joinDate,
		BillingDate:      24,
		BillingType:      "fixed",
		BillingDeadline:  1,
		CustomPrice:      &customPrice,
		Discount:         0,
		AdditionalFee:    10000,
		FeeDescription:   "Biaya admin",
		Status:           "active",
		ConnectionStatus: "online",
		Notes:            "",
		CreatedAt:        joinDate,
		UpdatedAt:        joinDate,
		ACSURL:           &acsURL,
		Package: &model.Package{
			ID:            packageID,
			TenantID:      "ignored",
			Name:          "Paket 50",
			BandwidthUp:   50,
			BandwidthDown: 50,
			Price:         200000,
			BurstLimit:    "65",
			AddressList:   "paket-50",
		},
		Router: &model.Router{
			ID:           routerID,
			TenantID:     "ignored",
			Name:         "PENEGAK",
			VPNIP:        "10.10.0.3",
			RADIUSSecret: "secret-should-not-leak",
			CoAPort:      3799,
		},
		CurrentInvoice: &model.Invoice{
			ID:            "inv-1",
			TenantID:      "tenant-1",
			CustomerID:    "cust-1",
			InvoiceNumber: "202605-260501001",
			PeriodMonth:   5,
			PeriodYear:    2026,
			PackagePrice:  200000,
			AdditionalFee: 10000,
			TotalAmount:   210000,
			Status:        "paid",
			DueDate:       dueDate,
			PaidAt:        &startedAt,
			PaidAmount:    &invoicePaidAmount,
			PaymentMethod: &paymentMethod,
			AutoGenerated: true,
		},
		ActiveSession: &model.RadiusSession{
			ID:                  "sess-1",
			TenantID:            "tenant-1",
			SessionID:           "816000d2",
			Username:            "2605017725",
			NASIPAddress:        "10.10.0.3",
			FramedIP:            "192.168.100.11",
			InputOctets:         12345,
			OutputOctets:        67890,
			RealtimeDownloadBps: 12500000,
			RealtimeUploadBps:   2500000,
			RealtimeSampledAt:   &startedAt,
			Status:              "active",
			StartedAt:           startedAt,
		},
		ONT: &model.ONT{
			ID:            "ont-1",
			SerialNumber:  "HWTC101245E8",
			Model:         &modelName,
			Vendor:        &vendorName,
			Status:        "active",
			ProvisionedAt: &provisionedAt,
			StatusDetail: &model.ONTStatusDetail{
				DeviceID:             "HWTC-ZL-2113X-HWTC101245E8",
				SoftwareVersion:      "ZL_V2.2.2.8",
				Uptime:               &uptime,
				RxPower:              &rxPower,
				TxPower:              &txPower,
				WiFiSSID:             "CGOL",
				WiFiPasswordSource:   "not_reported",
				WiFiSecurity:         "WPAand11i",
				WiFiSecurityModes:    []string{"WPA", "11i"},
				WANIP:                "192.168.100.11",
				LastInform:           "2026-05-07T00:02:46.359Z",
				ConnectedHostCount:   4,
				ConnectedHostsSource: "count_only",
			},
			Actions: &model.ONTAvailableActions{
				CanRestart:    true,
				CanManageWiFi: true,
			},
		},
	})

	encoded, err := json.Marshal(resp)
	if err != nil {
		t.Fatalf("marshal response: %v", err)
	}

	var payload map[string]any
	if err := json.Unmarshal(encoded, &payload); err != nil {
		t.Fatalf("unmarshal payload: %v", err)
	}

	if _, ok := payload["connection_status"]; ok {
		t.Fatalf("top-level connection_status should not be exposed")
	}
	if _, ok := payload["current_invoice"]; ok {
		t.Fatalf("current_invoice should live under billing")
	}
	if _, ok := payload["active_session"]; ok {
		t.Fatalf("active_session should live under connection")
	}

	connection := payload["connection"].(map[string]any)
	if got := connection["status"]; got != "online" {
		t.Fatalf("unexpected connection status: %v", got)
	}
	if got := connection["current_ip"]; got != "192.168.100.11" {
		t.Fatalf("unexpected current_ip: %v", got)
	}
	if got := connection["download"]; got != float64(67890) {
		t.Fatalf("unexpected download: %v", got)
	}
	if got := connection["upload"]; got != float64(12345) {
		t.Fatalf("unexpected upload: %v", got)
	}
	if got := connection["realtime_download_mbps"]; got != 12.5 {
		t.Fatalf("unexpected realtime download Mbps: %v", got)
	}
	if got := connection["realtime_upload_mbps"]; got != 2.5 {
		t.Fatalf("unexpected realtime upload Mbps: %v", got)
	}
	if got := connection["realtime_sampled_at"]; got == nil {
		t.Fatalf("realtime sampled at should be present")
	}

	activeSession := connection["active_session"].(map[string]any)
	if _, ok := activeSession["username"]; ok {
		t.Fatalf("session username should not duplicate top-level access data")
	}
	if _, ok := activeSession["framed_ip"]; ok {
		t.Fatalf("session framed_ip should be normalized into connection.current_ip")
	}

	billing := payload["billing"].(map[string]any)
	if _, ok := billing["current_invoice"]; !ok {
		t.Fatalf("billing.current_invoice is missing")
	}

	packagePayload := payload["package"].(map[string]any)
	if _, ok := packagePayload["tenant_id"]; ok {
		t.Fatalf("package tenant_id should not be exposed")
	}

	routerPayload := payload["router"].(map[string]any)
	if _, ok := routerPayload["radius_secret"]; ok {
		t.Fatalf("router radius_secret should not be exposed")
	}

	ontPayload := payload["ont"].(map[string]any)
	if _, ok := ontPayload["status_detail"]; ok {
		t.Fatalf("raw ont status_detail should not be exposed")
	}
	wifiPayload, ok := ontPayload["wifi"].(map[string]any)
	if !ok {
		t.Fatalf("ont wifi section is missing")
	}
	if _, ok := ontPayload["connected_hosts"]; !ok {
		t.Fatalf("ont connected_hosts section is missing")
	}
	if got := wifiPayload["ssid"]; got != "CGOL" {
		t.Fatalf("unexpected wifi ssid: %v", got)
	}
	if got := wifiPayload["password"]; got != "" {
		t.Fatalf("wifi password key should exist even when empty: %v", got)
	}
}

func TestMapCustomerBillingUsesExplicitInvoiceAndDueDates(t *testing.T) {
	now := time.Date(2026, time.May, 24, 8, 0, 0, 0, time.UTC)
	billing := mapCustomerBilling(&model.Customer{
		JoinDate:        time.Date(2026, time.January, 1, 0, 0, 0, 0, time.UTC),
		BillingDate:     24,
		BillingType:     "fixed",
		BillingDeadline: 1,
	}, now)

	wantInvoiceDate := time.Date(2026, time.May, 24, 0, 0, 0, 0, time.UTC)
	wantDueDate := time.Date(2026, time.June, 1, 0, 0, 0, 0, time.UTC)
	if billing.InvoiceDate == nil || !billing.InvoiceDate.Equal(wantInvoiceDate) {
		t.Fatalf("billing.InvoiceDate = %v, want %v", billing.InvoiceDate, wantInvoiceDate)
	}
	if billing.BillingDueDate == nil || !billing.BillingDueDate.Equal(wantDueDate) {
		t.Fatalf("billing.BillingDueDate = %v, want %v", billing.BillingDueDate, wantDueDate)
	}
}

func TestMapCustomerBillingShowsNextCycleWhenLatestInvoicePaid(t *testing.T) {
	now := time.Date(2026, time.May, 25, 8, 0, 0, 0, time.UTC)
	paidAt := time.Date(2026, time.May, 25, 9, 0, 0, 0, time.UTC)
	billing := mapCustomerBilling(&model.Customer{
		JoinDate:        time.Date(2026, time.January, 1, 0, 0, 0, 0, time.UTC),
		BillingDate:     24,
		BillingType:     "fixed",
		BillingDeadline: 1,
		CurrentInvoice: &model.Invoice{
			PeriodMonth: 6,
			PeriodYear:  2026,
			Status:      "paid",
			DueDate:     time.Date(2026, time.June, 1, 0, 0, 0, 0, time.UTC),
			PaidAt:      &paidAt,
		},
	}, now)

	wantInvoiceDate := time.Date(2026, time.June, 24, 0, 0, 0, 0, time.UTC)
	wantDueDate := time.Date(2026, time.July, 1, 0, 0, 0, 0, time.UTC)
	if billing.InvoiceDate == nil || !billing.InvoiceDate.Equal(wantInvoiceDate) {
		t.Fatalf("billing.InvoiceDate = %v, want %v", billing.InvoiceDate, wantInvoiceDate)
	}
	if billing.BillingDueDate == nil || !billing.BillingDueDate.Equal(wantDueDate) {
		t.Fatalf("billing.BillingDueDate = %v, want %v", billing.BillingDueDate, wantDueDate)
	}
}

func TestNewCustomerDetailResponseHidesInvoiceAndDueDatesForFreeBilling(t *testing.T) {
	resp := newCustomerDetailResponse(&model.Customer{
		ID:       "cust-free",
		TenantID: "tenant-1",
		Name:     "Pelanggan Free",
		JoinDate: time.Date(2026, time.January, 1, 0, 0, 0, 0, time.UTC),
		Package: &model.Package{
			ID:    "pkg-free",
			Name:  "Free",
			Price: 0,
		},
		BillingDate:     24,
		BillingType:     "fixed",
		BillingDeadline: 1,
	})

	encoded, err := json.Marshal(resp)
	if err != nil {
		t.Fatalf("marshal response: %v", err)
	}

	var payload map[string]any
	if err := json.Unmarshal(encoded, &payload); err != nil {
		t.Fatalf("unmarshal payload: %v", err)
	}

	billingPayload := payload["billing"].(map[string]any)
	if _, ok := billingPayload["invoice_date"]; ok {
		t.Fatalf("invoice_date should be omitted for free billing: %v", billingPayload["invoice_date"])
	}
	if _, ok := billingPayload["billing_due_date"]; ok {
		t.Fatalf("billing_due_date should be omitted for free billing: %v", billingPayload["billing_due_date"])
	}
}

func TestNewCustomerDetailResponseFallsBackToCachedWiFi(t *testing.T) {
	ssid := "BINJAI-NET"
	password := "rahasia123"
	security := "11i"
	source := "set_request"

	resp := newCustomerDetailResponse(&model.Customer{
		ID:       "cust-2",
		TenantID: "tenant-1",
		Name:     "Pelanggan",
		ONT: &model.ONT{
			ID:                    "ont-2",
			SerialNumber:          "HWTC0002",
			Status:                "active",
			LastKnownWiFiSSID:     &ssid,
			LastKnownWiFiPassword: &password,
			LastKnownWiFiSecurity: &security,
			LastKnownWiFiSource:   &source,
		},
	})

	encoded, err := json.Marshal(resp)
	if err != nil {
		t.Fatalf("marshal response: %v", err)
	}

	var payload map[string]any
	if err := json.Unmarshal(encoded, &payload); err != nil {
		t.Fatalf("unmarshal payload: %v", err)
	}

	ontPayload := payload["ont"].(map[string]any)
	wifiPayload := ontPayload["wifi"].(map[string]any)
	if got := wifiPayload["ssid"]; got != ssid {
		t.Fatalf("unexpected cached ssid: %v", got)
	}
	if got := wifiPayload["password"]; got != password {
		t.Fatalf("unexpected cached password: %v", got)
	}
	if got := wifiPayload["password_source"]; got != "last_sent" {
		t.Fatalf("unexpected password source: %v", got)
	}
	if got := wifiPayload["password_reported"]; got != false {
		t.Fatalf("cached password must not be marked as device-reported: %v", got)
	}
}

func TestNewCustomerDetailResponseDefaultsConnectionCounters(t *testing.T) {
	resp := newCustomerDetailResponse(&model.Customer{
		ID:             "cust-3",
		TenantID:       "tenant-1",
		ConnectionType: "pppoe",
		Status:         "active",
	})

	encoded, err := json.Marshal(resp)
	if err != nil {
		t.Fatalf("marshal response: %v", err)
	}

	var payload map[string]any
	if err := json.Unmarshal(encoded, &payload); err != nil {
		t.Fatalf("unmarshal payload: %v", err)
	}

	connection := payload["connection"].(map[string]any)
	if got := connection["download"]; got != float64(0) {
		t.Fatalf("unexpected default download: %v", got)
	}
	if got := connection["upload"]; got != float64(0) {
		t.Fatalf("unexpected default upload: %v", got)
	}
	if got := connection["realtime_download_mbps"]; got != float64(0) {
		t.Fatalf("unexpected default realtime download: %v", got)
	}
	if got := connection["realtime_upload_mbps"]; got != float64(0) {
		t.Fatalf("unexpected default realtime upload: %v", got)
	}
}
