package handler

import (
	"time"

	"github.com/candrasyahputra/radius-server/internal/model"
	"github.com/candrasyahputra/radius-server/internal/pkg/billing"
)

type customerDetailResponse struct {
	ID           string                     `json:"id"`
	TenantID     string                     `json:"tenant_id"`
	CustomerCode string                     `json:"customer_code"`
	Name         string                     `json:"name"`
	NIK          string                     `json:"nik"`
	Phone        string                     `json:"phone"`
	Email        string                     `json:"email"`
	Address      string                     `json:"address"`
	Latitude     *float64                   `json:"latitude,omitempty"`
	Longitude    *float64                   `json:"longitude,omitempty"`
	PackageID    *string                    `json:"package_id,omitempty"`
	RouterID     *string                    `json:"router_id,omitempty"`
	ODPPortID    *string                    `json:"odp_port_id,omitempty"`
	ResellerID   *string                    `json:"reseller_id,omitempty"`
	Status       string                     `json:"status"`
	Notes        string                     `json:"notes"`
	Access       customerAccessResponse     `json:"access"`
	Billing      customerBillingResponse    `json:"billing"`
	Connection   customerConnectionResponse `json:"connection"`
	Package      *customerPackageResponse   `json:"package,omitempty"`
	Router       *customerRouterResponse    `json:"router,omitempty"`
	ONT          *customerONTResponse       `json:"ont,omitempty"`
	CreatedAt    time.Time                  `json:"created_at"`
	UpdatedAt    time.Time                  `json:"updated_at"`
}

type customerAccessResponse struct {
	PPPoEUsername string  `json:"pppoe_username,omitempty"`
	PPPoEPassword string  `json:"pppoe_password,omitempty"`
	ACSURL        *string `json:"acs_url,omitempty"`
}

type customerBillingResponse struct {
	JoinDate        time.Time                `json:"join_date"`
	BillingDate     int                      `json:"billing_date"`
	InvoiceDate     *time.Time               `json:"invoice_date,omitempty"`
	BillingType     string                   `json:"billing_type"`
	BillingDeadline int                      `json:"billing_deadline"`
	BillingDueDate  *time.Time               `json:"billing_due_date,omitempty"`
	CustomPrice     *int64                   `json:"custom_price,omitempty"`
	Discount        int64                    `json:"discount"`
	AdditionalFee   int64                    `json:"additional_fee"`
	FeeDescription  string                   `json:"fee_description"`
	CurrentInvoice  *customerInvoiceResponse `json:"current_invoice,omitempty"`
}

type customerConnectionResponse struct {
	Type                 string                         `json:"type"`
	Status               string                         `json:"status"`
	ConfiguredIP         string                         `json:"configured_ip,omitempty"`
	CurrentIP            string                         `json:"current_ip,omitempty"`
	Download             int64                          `json:"download"`
	Upload               int64                          `json:"upload"`
	RealtimeDownloadMbps float64                        `json:"realtime_download_mbps"`
	RealtimeUploadMbps   float64                        `json:"realtime_upload_mbps"`
	RealtimeSampledAt    *time.Time                     `json:"realtime_sampled_at,omitempty"`
	ActiveSession        *customerActiveSessionResponse `json:"active_session,omitempty"`
}

type customerPackageResponse struct {
	ID            string `json:"id"`
	Name          string `json:"name,omitempty"`
	BandwidthUp   int    `json:"bandwidth_up,omitempty"`
	BandwidthDown int    `json:"bandwidth_down,omitempty"`
	Price         int64  `json:"price,omitempty"`
	BurstLimit    string `json:"burst_limit,omitempty"`
	AddressList   string `json:"address_list,omitempty"`
}

type customerRouterResponse struct {
	ID      string `json:"id"`
	Name    string `json:"name,omitempty"`
	VPNIP   string `json:"vpn_ip,omitempty"`
	CoAPort int    `json:"coa_port,omitempty"`
}

type customerInvoiceResponse struct {
	ID             string     `json:"id"`
	InvoiceNumber  string     `json:"invoice_number,omitempty"`
	PeriodMonth    int        `json:"period_month"`
	PeriodYear     int        `json:"period_year"`
	PackagePrice   int64      `json:"package_price"`
	Discount       int64      `json:"discount"`
	AdditionalFee  int64      `json:"additional_fee"`
	FeeDescription string     `json:"fee_description,omitempty"`
	TotalAmount    int64      `json:"total_amount"`
	Status         string     `json:"status,omitempty"`
	DueDate        time.Time  `json:"due_date"`
	PaidAt         *time.Time `json:"paid_at,omitempty"`
	PaidAmount     *int64     `json:"paid_amount,omitempty"`
	PaymentMethod  *string    `json:"payment_method,omitempty"`
	AutoGenerated  bool       `json:"auto_generated"`
}

type customerActiveSessionResponse struct {
	ID             string     `json:"id"`
	SessionID      string     `json:"session_id,omitempty"`
	NASIPAddress   string     `json:"nas_ip_address,omitempty"`
	CallerID       string     `json:"caller_id,omitempty"`
	InputOctets    int64      `json:"input_octets"`
	OutputOctets   int64      `json:"output_octets"`
	StartedAt      time.Time  `json:"started_at"`
	UpdatedAt      *time.Time `json:"updated_at,omitempty"`
	EndedAt        *time.Time `json:"ended_at,omitempty"`
	SessionTime    int        `json:"session_time"`
	TerminateCause string     `json:"terminate_cause,omitempty"`
}

type customerONTResponse struct {
	ID             string                             `json:"id"`
	SerialNumber   string                             `json:"serial_number,omitempty"`
	Model          *string                            `json:"model,omitempty"`
	Vendor         *string                            `json:"vendor,omitempty"`
	Status         string                             `json:"status,omitempty"`
	ProvisionedAt  *time.Time                         `json:"provisioned_at,omitempty"`
	LastOnlineAt   *time.Time                         `json:"last_online_at,omitempty"`
	Device         *customerONTDeviceResponse         `json:"device,omitempty"`
	Signal         *customerONTSignalResponse         `json:"signal,omitempty"`
	WiFi           *customerONTWiFiResponse           `json:"wifi,omitempty"`
	Network        *customerONTNetworkResponse        `json:"network,omitempty"`
	ConnectedHosts *customerONTConnectedHostsResponse `json:"connected_hosts,omitempty"`
	Actions        *model.ONTAvailableActions         `json:"actions,omitempty"`
}

type customerONTDeviceResponse struct {
	DeviceID        string `json:"device_id,omitempty"`
	SoftwareVersion string `json:"software_version,omitempty"`
	LastInform      string `json:"last_inform,omitempty"`
	DataRealtime    bool   `json:"data_realtime"`
	Uptime          *int64 `json:"uptime,omitempty"`
}

type customerONTSignalResponse struct {
	RxPower *float64 `json:"rx_power,omitempty"`
	TxPower *float64 `json:"tx_power,omitempty"`
}

type customerONTWiFiResponse struct {
	SSID             string   `json:"ssid"`
	Password         string   `json:"password"`
	PasswordReported bool     `json:"password_reported"`
	PasswordSource   string   `json:"password_source,omitempty"`
	Security         string   `json:"security,omitempty"`
	SecurityModes    []string `json:"security_modes,omitempty"`
}

type customerONTNetworkResponse struct {
	WANIP string `json:"wan_ip,omitempty"`
}

type customerONTConnectedHostsResponse struct {
	Count    int                      `json:"count"`
	Complete bool                     `json:"complete"`
	Source   string                   `json:"source,omitempty"`
	Items    []model.ONTConnectedHost `json:"items,omitempty"`
}

func newCustomerDetailResponse(customer *model.Customer) *customerDetailResponse {
	if customer == nil {
		return nil
	}

	return &customerDetailResponse{
		ID:           customer.ID,
		TenantID:     customer.TenantID,
		CustomerCode: customer.CustomerCode,
		Name:         customer.Name,
		NIK:          customer.NIK,
		Phone:        customer.Phone,
		Email:        customer.Email,
		Address:      customer.Address,
		Latitude:     customer.Latitude,
		Longitude:    customer.Longitude,
		PackageID:    customer.PackageID,
		RouterID:     customer.RouterID,
		ODPPortID:    customer.ODPPortID,
		ResellerID:   customer.ResellerID,
		Status:       customer.Status,
		Notes:        customer.Notes,
		Access: customerAccessResponse{
			PPPoEUsername: customer.PPPoEUsername,
			PPPoEPassword: customer.PPPoEPassword,
			ACSURL:        customer.ACSURL,
		},
		Billing: mapCustomerBilling(customer, time.Now()),
		Connection: customerConnectionResponse{
			Type:                 customer.ConnectionType,
			Status:               deriveCustomerConnectionStatus(customer),
			ConfiguredIP:         customer.IPAddress,
			CurrentIP:            deriveCustomerCurrentIP(customer),
			Download:             deriveCustomerDownload(customer),
			Upload:               deriveCustomerUpload(customer),
			RealtimeDownloadMbps: deriveCustomerRealtimeDownloadMbps(customer),
			RealtimeUploadMbps:   deriveCustomerRealtimeUploadMbps(customer),
			RealtimeSampledAt:    deriveCustomerRealtimeSampledAt(customer),
			ActiveSession:        mapCustomerActiveSession(customer.ActiveSession),
		},
		Package:   mapCustomerPackage(customer.Package),
		Router:    mapCustomerRouter(customer.Router),
		ONT:       mapCustomerONT(customer.ONT),
		CreatedAt: customer.CreatedAt,
		UpdatedAt: customer.UpdatedAt,
	}
}

func mapCustomerBilling(customer *model.Customer, now time.Time) customerBillingResponse {
	if customer == nil {
		return customerBillingResponse{}
	}

	var invoiceDate *time.Time
	var dueDate *time.Time
	if !customerHasFreeBilling(customer) {
		resolvedInvoiceDate, resolvedDueDate := deriveCustomerBillingDates(customer, now)
		invoiceDate = &resolvedInvoiceDate
		dueDate = &resolvedDueDate
	}

	return customerBillingResponse{
		JoinDate:        customer.JoinDate,
		BillingDate:     customer.BillingDate,
		InvoiceDate:     invoiceDate,
		BillingType:     customer.BillingType,
		BillingDeadline: customer.BillingDeadline,
		BillingDueDate:  dueDate,
		CustomPrice:     customer.CustomPrice,
		Discount:        customer.Discount,
		AdditionalFee:   customer.AdditionalFee,
		FeeDescription:  customer.FeeDescription,
		CurrentInvoice:  mapCustomerInvoice(customer.CurrentInvoice),
	}
}

func customerHasFreeBilling(customer *model.Customer) bool {
	price, ok := resolvedCustomerBillingPrice(customer)
	if !ok {
		return false
	}

	return price-customer.Discount+customer.AdditionalFee <= 0
}

func resolvedCustomerBillingPrice(customer *model.Customer) (int64, bool) {
	if customer == nil {
		return 0, false
	}
	if customer.CustomPrice != nil {
		return *customer.CustomPrice, true
	}
	if customer.Package != nil {
		return customer.Package.Price, true
	}
	return 0, false
}

func normalizeCustomerBillingDeadline(customer *model.Customer) int {
	if customer == nil {
		return 1
	}

	deadlineDay := customer.BillingDeadline
	if deadlineDay <= 0 && !customer.JoinDate.IsZero() {
		deadlineDay = customer.JoinDate.Day()
	}
	return billing.NormalizeDay(deadlineDay)
}

func deriveCustomerConnectionStatus(customer *model.Customer) string {
	if customer == nil {
		return ""
	}
	if customer.Status == "isolated" {
		return "isolated"
	}
	if customer.ConnectionStatus != "" {
		return customer.ConnectionStatus
	}
	if customer.ActiveSession != nil {
		return "online"
	}
	return "offline"
}

func deriveCustomerCurrentIP(customer *model.Customer) string {
	if customer == nil {
		return ""
	}
	if customer.ActiveSession != nil && customer.ActiveSession.FramedIP != "" {
		return customer.ActiveSession.FramedIP
	}
	if customer.ONT != nil && customer.ONT.StatusDetail != nil && customer.ONT.StatusDetail.WANIP != "" {
		return customer.ONT.StatusDetail.WANIP
	}
	return customer.IPAddress
}

func deriveCustomerDownload(customer *model.Customer) int64 {
	if customer == nil || customer.ActiveSession == nil {
		return 0
	}
	return customer.ActiveSession.OutputOctets
}

func deriveCustomerUpload(customer *model.Customer) int64 {
	if customer == nil || customer.ActiveSession == nil {
		return 0
	}
	return customer.ActiveSession.InputOctets
}

func deriveCustomerRealtimeDownloadMbps(customer *model.Customer) float64 {
	if customer == nil || customer.ActiveSession == nil {
		return 0
	}
	return bpsToMbps(customer.ActiveSession.RealtimeDownloadBps)
}

func deriveCustomerRealtimeUploadMbps(customer *model.Customer) float64 {
	if customer == nil || customer.ActiveSession == nil {
		return 0
	}
	return bpsToMbps(customer.ActiveSession.RealtimeUploadBps)
}

func deriveCustomerRealtimeSampledAt(customer *model.Customer) *time.Time {
	if customer == nil || customer.ActiveSession == nil {
		return nil
	}
	return customer.ActiveSession.RealtimeSampledAt
}

func bpsToMbps(bps int64) float64 {
	if bps <= 0 {
		return 0
	}
	return float64(bps) / 1000000
}

func mapCustomerPackage(pkg *model.Package) *customerPackageResponse {
	if pkg == nil {
		return nil
	}

	return &customerPackageResponse{
		ID:            pkg.ID,
		Name:          pkg.Name,
		BandwidthUp:   pkg.BandwidthUp,
		BandwidthDown: pkg.BandwidthDown,
		Price:         pkg.Price,
		BurstLimit:    pkg.BurstLimit,
		AddressList:   pkg.AddressList,
	}
}

func mapCustomerRouter(router *model.Router) *customerRouterResponse {
	if router == nil {
		return nil
	}

	return &customerRouterResponse{
		ID:      router.ID,
		Name:    router.Name,
		VPNIP:   router.VPNIP,
		CoAPort: router.CoAPort,
	}
}

func mapCustomerInvoice(invoice *model.Invoice) *customerInvoiceResponse {
	if invoice == nil {
		return nil
	}

	return &customerInvoiceResponse{
		InvoiceNumber:  invoice.InvoiceNumber,
		PeriodMonth:    invoice.PeriodMonth,
		PeriodYear:     invoice.PeriodYear,
		PackagePrice:   invoice.PackagePrice,
		Discount:       invoice.Discount,
		AdditionalFee:  invoice.AdditionalFee,
		FeeDescription: invoice.FeeDescription,
		TotalAmount:    invoice.TotalAmount,
		Status:         invoice.Status,
		DueDate:        invoice.DueDate,
		PaidAt:         invoice.PaidAt,
		PaidAmount:     invoice.PaidAmount,
		PaymentMethod:  invoice.PaymentMethod,
		AutoGenerated:  invoice.AutoGenerated,
	}
}

func deriveCustomerBillingDates(customer *model.Customer, now time.Time) (time.Time, time.Time) {
	deadlineDay := normalizeCustomerBillingDeadline(customer)
	invoiceDay := normalizedCustomerInvoiceDay(customer, deadlineDay)

	if customer == nil || customer.CurrentInvoice == nil {
		return billing.CurrentCycleDates(now, invoiceDay, deadlineDay)
	}

	if customer.BillingType != "fixed" && customer.CurrentInvoice.Status == "paid" && customer.CurrentInvoice.PaidAt != nil && customer.CurrentInvoice.PaidAt.After(customer.CurrentInvoice.DueDate) {
		deadlineDay = billing.NormalizeDay(customer.CurrentInvoice.PaidAt.Day())
		invoiceDay = billing.InvoiceDayFromDueDay(deadlineDay)
	}

	dueMonth := customer.CurrentInvoice.PeriodMonth
	dueYear := customer.CurrentInvoice.PeriodYear
	if dueMonth <= 0 || dueYear <= 0 {
		return billing.CurrentCycleDates(now, invoiceDay, deadlineDay)
	}

	if customer.CurrentInvoice.Status == "paid" {
		nextCycle := time.Date(dueYear, time.Month(dueMonth), 1, 0, 0, 0, 0, time.UTC).AddDate(0, 1, 0)
		return billing.CycleDates(invoiceDay, deadlineDay, int(nextCycle.Month()), nextCycle.Year())
	}

	invoiceDate, _ := billing.CycleDates(invoiceDay, deadlineDay, dueMonth, dueYear)
	return invoiceDate, customer.CurrentInvoice.DueDate
}

func normalizedCustomerInvoiceDay(customer *model.Customer, deadlineDay int) int {
	if customer == nil {
		return billing.InvoiceDayFromDueDay(deadlineDay)
	}
	if customer.BillingDate > 0 {
		return billing.NormalizeDay(customer.BillingDate)
	}
	return billing.InvoiceDayFromDueDay(deadlineDay)
}

func mapCustomerActiveSession(session *model.RadiusSession) *customerActiveSessionResponse {
	if session == nil {
		return nil
	}

	return &customerActiveSessionResponse{
		ID:             session.ID,
		SessionID:      session.SessionID,
		NASIPAddress:   session.NASIPAddress,
		CallerID:       session.CallerID,
		InputOctets:    session.InputOctets,
		OutputOctets:   session.OutputOctets,
		StartedAt:      session.StartedAt,
		UpdatedAt:      session.UpdatedAt,
		EndedAt:        session.EndedAt,
		SessionTime:    session.SessionTime,
		TerminateCause: session.TerminateCause,
	}
}

func mapCustomerONT(ont *model.ONT) *customerONTResponse {
	if ont == nil {
		return nil
	}

	resp := &customerONTResponse{
		ID:            ont.ID,
		SerialNumber:  ont.SerialNumber,
		Model:         ont.Model,
		Vendor:        ont.Vendor,
		Status:        ont.Status,
		ProvisionedAt: ont.ProvisionedAt,
		LastOnlineAt:  ont.LastOnlineAt,
		WiFi:          mapCustomerONTWiFi(ont),
		Actions:       ont.Actions,
	}

	if ont.StatusDetail == nil {
		return resp
	}

	resp.Device = mapCustomerONTDevice(ont.StatusDetail)
	resp.Signal = mapCustomerONTSignal(ont.StatusDetail)
	resp.Network = mapCustomerONTNetwork(ont.StatusDetail)
	resp.ConnectedHosts = mapCustomerONTConnectedHosts(ont.StatusDetail)

	return resp
}

func mapCustomerONTDevice(detail *model.ONTStatusDetail) *customerONTDeviceResponse {
	if detail == nil {
		return nil
	}
	if detail.DeviceID == "" && detail.SoftwareVersion == "" && detail.LastInform == "" && detail.Uptime == nil && !detail.DataRealtime {
		return nil
	}

	return &customerONTDeviceResponse{
		DeviceID:        detail.DeviceID,
		SoftwareVersion: detail.SoftwareVersion,
		LastInform:      detail.LastInform,
		DataRealtime:    detail.DataRealtime,
		Uptime:          detail.Uptime,
	}
}

func mapCustomerONTSignal(detail *model.ONTStatusDetail) *customerONTSignalResponse {
	if detail == nil {
		return nil
	}
	if detail.RxPower == nil && detail.TxPower == nil {
		return nil
	}

	return &customerONTSignalResponse{
		RxPower: detail.RxPower,
		TxPower: detail.TxPower,
	}
}

func mapCustomerONTWiFi(ont *model.ONT) *customerONTWiFiResponse {
	if ont == nil {
		return nil
	}

	resp := &customerONTWiFiResponse{}
	if detail := ont.StatusDetail; detail != nil {
		resp.SSID = detail.WiFiSSID
		resp.Password = detail.WiFiPassword
		resp.PasswordReported = detail.WiFiPasswordReported
		resp.PasswordSource = detail.WiFiPasswordSource
		resp.Security = detail.WiFiSecurity
		resp.SecurityModes = detail.WiFiSecurityModes
	}

	if resp.SSID == "" && ont.LastKnownWiFiSSID != nil {
		resp.SSID = *ont.LastKnownWiFiSSID
	}
	if resp.Password == "" && ont.LastKnownWiFiPassword != nil {
		resp.Password = *ont.LastKnownWiFiPassword
	}
	if resp.PasswordSource == "" && ont.LastKnownWiFiSource != nil && *ont.LastKnownWiFiSource != "" {
		resp.PasswordSource = normalizeWiFiPasswordSource(*ont.LastKnownWiFiSource)
	}
	if resp.Password == "" {
		resp.PasswordReported = false
	}
	if resp.Security == "" && ont.LastKnownWiFiSecurity != nil {
		resp.Security = *ont.LastKnownWiFiSecurity
	}

	return resp
}

func normalizeWiFiPasswordSource(source string) string {
	switch source {
	case "", "set_request":
		return "last_sent"
	default:
		return source
	}
}

func mapCustomerONTNetwork(detail *model.ONTStatusDetail) *customerONTNetworkResponse {
	if detail == nil || detail.WANIP == "" {
		return nil
	}

	return &customerONTNetworkResponse{
		WANIP: detail.WANIP,
	}
}

func mapCustomerONTConnectedHosts(detail *model.ONTStatusDetail) *customerONTConnectedHostsResponse {
	if detail == nil {
		return nil
	}

	return &customerONTConnectedHostsResponse{
		Count:    detail.ConnectedHostCount,
		Complete: detail.ConnectedHostsComplete,
		Source:   detail.ConnectedHostsSource,
		Items:    detail.ConnectedHosts,
	}
}
