package repository

import (
	"context"
	"fmt"
	"strings"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/candrasyahputra/radius-server/internal/model"
	"github.com/candrasyahputra/radius-server/internal/pkg/id"
)

type InvoiceRepository interface {
	Create(ctx context.Context, invoice *model.Invoice) error
	FindByID(ctx context.Context, tenantID, invoiceID string) (*model.Invoice, error)
	FindByNumber(ctx context.Context, tenantID, invoiceNumber string) (*model.Invoice, error)
	FindByCustomerPeriod(ctx context.Context, tenantID, customerID string, month, year int) (*model.Invoice, error)
	FindCurrentByCustomer(ctx context.Context, tenantID, customerID string) (*model.Invoice, error)
	Update(ctx context.Context, invoice *model.Invoice) error
	UpdateStatus(ctx context.Context, tenantID, invoiceID, status string) error
	MarkPaid(ctx context.Context, invoice *model.Invoice) error
	Delete(ctx context.Context, tenantID, invoiceID string) error
	List(ctx context.Context, tenantID string, filter InvoiceFilter) ([]model.Invoice, int, error)
	ListByCustomer(ctx context.Context, tenantID, customerID string, page, perPage int) ([]model.Invoice, int, error)
	ListUnpaidDue(ctx context.Context, tenantID string, dueDate string) ([]model.Invoice, error)
	ListOverdueForIsolir(ctx context.Context, tenantID string, cutoffDate string) ([]model.Invoice, error)
	CreateBatch(ctx context.Context, invoices []model.Invoice) error
	HasUnpaidInvoice(ctx context.Context, tenantID, customerID string) (bool, error)
	FindLastPaidInvoice(ctx context.Context, tenantID, customerID string) (*model.Invoice, error)
	CountPaidInvoices(ctx context.Context, tenantID, customerID string) (int, error)
}

type InvoiceFilter struct {
	Search      string
	CustomerID  string
	Status      string
	PeriodMonth int
	PeriodYear  int
	Page        int
	PerPage     int
}

type invoiceRepository struct {
	db *pgxpool.Pool
}

func NewInvoiceRepository(db *pgxpool.Pool) InvoiceRepository {
	return &invoiceRepository{db: db}
}

func (r *invoiceRepository) Create(ctx context.Context, invoice *model.Invoice) error {
	invoice.ID = id.New()
	_, err := r.db.Exec(ctx, `
		INSERT INTO invoices (
			id, tenant_id, customer_id, invoice_number, period_month, period_year,
			package_price, discount, additional_fee, fee_description, total_amount,
			status, due_date, notes, auto_generated
		) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15)
	`,
		invoice.ID, invoice.TenantID, invoice.CustomerID, invoice.InvoiceNumber,
		invoice.PeriodMonth, invoice.PeriodYear, invoice.PackagePrice, invoice.Discount,
		invoice.AdditionalFee, invoice.FeeDescription, invoice.TotalAmount,
		invoice.Status, invoice.DueDate, invoice.Notes, invoice.AutoGenerated,
	)
	return err
}

func (r *invoiceRepository) FindByID(ctx context.Context, tenantID, invoiceID string) (*model.Invoice, error) {
	var inv model.Invoice
	var custName, custCode, custPhone string
	err := r.db.QueryRow(ctx, `
		SELECT i.id, i.tenant_id, i.customer_id, i.invoice_number, i.period_month, i.period_year,
		       i.package_price, i.discount, i.additional_fee, COALESCE(i.fee_description,''), i.total_amount,
		       i.status, i.due_date, i.paid_at, i.paid_amount, i.payment_method, COALESCE(i.notes,''),
		       i.auto_generated, i.created_at, i.updated_at,
		       c.name, c.customer_code, COALESCE(c.phone,'')
		FROM invoices i
		JOIN customers c ON c.id = i.customer_id
		WHERE i.id = $1 AND i.tenant_id = $2
	`, invoiceID, tenantID).Scan(
		&inv.ID, &inv.TenantID, &inv.CustomerID, &inv.InvoiceNumber, &inv.PeriodMonth, &inv.PeriodYear,
		&inv.PackagePrice, &inv.Discount, &inv.AdditionalFee, &inv.FeeDescription, &inv.TotalAmount,
		&inv.Status, &inv.DueDate, &inv.PaidAt, &inv.PaidAmount, &inv.PaymentMethod, &inv.Notes,
		&inv.AutoGenerated, &inv.CreatedAt, &inv.UpdatedAt,
		&custName, &custCode, &custPhone,
	)
	if err != nil {
		if err == pgx.ErrNoRows {
			return nil, nil
		}
		return nil, err
	}
	inv.Customer = &model.Customer{ID: inv.CustomerID, Name: custName, CustomerCode: custCode, Phone: custPhone}
	return &inv, nil
}

func (r *invoiceRepository) FindByNumber(ctx context.Context, tenantID, invoiceNumber string) (*model.Invoice, error) {
	var inv model.Invoice
	err := r.db.QueryRow(ctx, `
		SELECT id, tenant_id, customer_id, invoice_number, period_month, period_year,
		       package_price, discount, additional_fee, COALESCE(fee_description,''), total_amount,
		       status, due_date, paid_at, paid_amount, payment_method, COALESCE(notes,''),
		       auto_generated, created_at, updated_at
		FROM invoices
		WHERE invoice_number = $1 AND tenant_id = $2
	`, invoiceNumber, tenantID).Scan(
		&inv.ID, &inv.TenantID, &inv.CustomerID, &inv.InvoiceNumber, &inv.PeriodMonth, &inv.PeriodYear,
		&inv.PackagePrice, &inv.Discount, &inv.AdditionalFee, &inv.FeeDescription, &inv.TotalAmount,
		&inv.Status, &inv.DueDate, &inv.PaidAt, &inv.PaidAmount, &inv.PaymentMethod, &inv.Notes,
		&inv.AutoGenerated, &inv.CreatedAt, &inv.UpdatedAt,
	)
	if err != nil {
		if err == pgx.ErrNoRows {
			return nil, nil
		}
		return nil, err
	}
	return &inv, nil
}

func (r *invoiceRepository) FindByCustomerPeriod(ctx context.Context, tenantID, customerID string, month, year int) (*model.Invoice, error) {
	var inv model.Invoice
	err := r.db.QueryRow(ctx, `
		SELECT id, tenant_id, customer_id, invoice_number, period_month, period_year,
		       package_price, discount, additional_fee, COALESCE(fee_description,''), total_amount,
		       status, due_date, paid_at, paid_amount, payment_method, COALESCE(notes,''),
		       auto_generated, created_at, updated_at
		FROM invoices
		WHERE tenant_id = $1 AND customer_id = $2 AND period_month = $3 AND period_year = $4
	`, tenantID, customerID, month, year).Scan(
		&inv.ID, &inv.TenantID, &inv.CustomerID, &inv.InvoiceNumber, &inv.PeriodMonth, &inv.PeriodYear,
		&inv.PackagePrice, &inv.Discount, &inv.AdditionalFee, &inv.FeeDescription, &inv.TotalAmount,
		&inv.Status, &inv.DueDate, &inv.PaidAt, &inv.PaidAmount, &inv.PaymentMethod, &inv.Notes,
		&inv.AutoGenerated, &inv.CreatedAt, &inv.UpdatedAt,
	)
	if err != nil {
		if err == pgx.ErrNoRows {
			return nil, nil
		}
		return nil, err
	}
	return &inv, nil
}

func (r *invoiceRepository) FindCurrentByCustomer(ctx context.Context, tenantID, customerID string) (*model.Invoice, error) {
	var inv model.Invoice
	err := r.db.QueryRow(ctx, `
		SELECT id, tenant_id, customer_id, invoice_number, period_month, period_year,
		       package_price, discount, additional_fee, COALESCE(fee_description,''), total_amount,
		       status, due_date, paid_at, paid_amount, payment_method, COALESCE(notes,''),
		       auto_generated, created_at, updated_at
		FROM invoices
		WHERE tenant_id = $1 AND customer_id = $2
		ORDER BY
			CASE WHEN status = 'unpaid' THEN 0 ELSE 1 END,
			CASE WHEN status = 'unpaid' THEN due_date END ASC,
			period_year DESC,
			period_month DESC,
			created_at DESC
		LIMIT 1
	`, tenantID, customerID).Scan(
		&inv.ID, &inv.TenantID, &inv.CustomerID, &inv.InvoiceNumber, &inv.PeriodMonth, &inv.PeriodYear,
		&inv.PackagePrice, &inv.Discount, &inv.AdditionalFee, &inv.FeeDescription, &inv.TotalAmount,
		&inv.Status, &inv.DueDate, &inv.PaidAt, &inv.PaidAmount, &inv.PaymentMethod, &inv.Notes,
		&inv.AutoGenerated, &inv.CreatedAt, &inv.UpdatedAt,
	)
	if err != nil {
		if err == pgx.ErrNoRows {
			return nil, nil
		}
		return nil, err
	}
	return &inv, nil
}

func (r *invoiceRepository) Update(ctx context.Context, invoice *model.Invoice) error {
	_, err := r.db.Exec(ctx, `
		UPDATE invoices SET
			package_price = $1, discount = $2, additional_fee = $3, fee_description = $4,
			total_amount = $5, notes = $6, due_date = $7, updated_at = NOW()
		WHERE id = $8 AND tenant_id = $9
	`,
		invoice.PackagePrice, invoice.Discount, invoice.AdditionalFee, invoice.FeeDescription,
		invoice.TotalAmount, invoice.Notes, invoice.DueDate,
		invoice.ID, invoice.TenantID,
	)
	return err
}

func (r *invoiceRepository) UpdateStatus(ctx context.Context, tenantID, invoiceID, status string) error {
	_, err := r.db.Exec(ctx, `
		UPDATE invoices SET status = $1, updated_at = NOW()
		WHERE id = $2 AND tenant_id = $3
	`, status, invoiceID, tenantID)
	return err
}

func (r *invoiceRepository) MarkPaid(ctx context.Context, invoice *model.Invoice) error {
	_, err := r.db.Exec(ctx, `
		UPDATE invoices SET
			status = 'paid', paid_at = NOW(), paid_amount = $1, payment_method = $2, updated_at = NOW()
		WHERE id = $3 AND tenant_id = $4
	`, invoice.PaidAmount, invoice.PaymentMethod, invoice.ID, invoice.TenantID)
	return err
}

func (r *invoiceRepository) Delete(ctx context.Context, tenantID, invoiceID string) error {
	_, err := r.db.Exec(ctx, `DELETE FROM invoices WHERE id = $1 AND tenant_id = $2`, invoiceID, tenantID)
	return err
}

func (r *invoiceRepository) List(ctx context.Context, tenantID string, filter InvoiceFilter) ([]model.Invoice, int, error) {
	var conditions []string
	var args []interface{}
	argIdx := 1

	conditions = append(conditions, fmt.Sprintf("i.tenant_id = $%d", argIdx))
	args = append(args, tenantID)
	argIdx++

	if filter.Search != "" {
		conditions = append(conditions, fmt.Sprintf("(i.invoice_number ILIKE $%d OR c.name ILIKE $%d)", argIdx, argIdx))
		args = append(args, "%"+filter.Search+"%")
		argIdx++
	}

	if filter.CustomerID != "" {
		conditions = append(conditions, fmt.Sprintf("i.customer_id = $%d", argIdx))
		args = append(args, filter.CustomerID)
		argIdx++
	}

	if filter.Status != "" {
		conditions = append(conditions, fmt.Sprintf("i.status = $%d", argIdx))
		args = append(args, filter.Status)
		argIdx++
	}

	if filter.PeriodMonth > 0 {
		conditions = append(conditions, fmt.Sprintf("i.period_month = $%d", argIdx))
		args = append(args, filter.PeriodMonth)
		argIdx++
	}

	if filter.PeriodYear > 0 {
		conditions = append(conditions, fmt.Sprintf("i.period_year = $%d", argIdx))
		args = append(args, filter.PeriodYear)
		argIdx++
	}

	where := "WHERE " + strings.Join(conditions, " AND ")

	var total int
	countQuery := "SELECT COUNT(*) FROM invoices i JOIN customers c ON c.id = i.customer_id " + where
	if err := r.db.QueryRow(ctx, countQuery, args...).Scan(&total); err != nil {
		return nil, 0, err
	}

	if filter.PerPage <= 0 {
		filter.PerPage = 20
	}
	if filter.Page <= 0 {
		filter.Page = 1
	}
	offset := (filter.Page - 1) * filter.PerPage

	dataQuery := fmt.Sprintf(`
		SELECT i.id, i.tenant_id, i.customer_id, i.invoice_number, i.period_month, i.period_year,
		       i.package_price, i.discount, i.additional_fee, COALESCE(i.fee_description,''), i.total_amount,
		       i.status, i.due_date, i.paid_at, i.paid_amount, i.payment_method, COALESCE(i.notes,''),
		       i.auto_generated, i.created_at, i.updated_at,
		       c.name, c.customer_code, COALESCE(c.phone,'')
		FROM invoices i
		JOIN customers c ON c.id = i.customer_id
		%s
		ORDER BY
			CASE WHEN i.status = 'unpaid' THEN 0 ELSE 1 END,
			CASE WHEN i.status = 'unpaid' THEN i.due_date END ASC,
			i.period_year DESC, i.period_month DESC, i.created_at DESC
		LIMIT $%d OFFSET $%d
	`, where, argIdx, argIdx+1)

	args = append(args, filter.PerPage, offset)

	rows, err := r.db.Query(ctx, dataQuery, args...)
	if err != nil {
		return nil, 0, err
	}
	defer rows.Close()

	var invoices []model.Invoice
	for rows.Next() {
		var inv model.Invoice
		var custName, custCode, custPhone string
		if err := rows.Scan(
			&inv.ID, &inv.TenantID, &inv.CustomerID, &inv.InvoiceNumber, &inv.PeriodMonth, &inv.PeriodYear,
			&inv.PackagePrice, &inv.Discount, &inv.AdditionalFee, &inv.FeeDescription, &inv.TotalAmount,
			&inv.Status, &inv.DueDate, &inv.PaidAt, &inv.PaidAmount, &inv.PaymentMethod, &inv.Notes,
			&inv.AutoGenerated, &inv.CreatedAt, &inv.UpdatedAt,
			&custName, &custCode, &custPhone,
		); err != nil {
			return nil, 0, err
		}
		inv.Customer = &model.Customer{ID: inv.CustomerID, Name: custName, CustomerCode: custCode, Phone: custPhone}
		invoices = append(invoices, inv)
	}

	return invoices, total, nil
}

func (r *invoiceRepository) ListByCustomer(ctx context.Context, tenantID, customerID string, page, perPage int) ([]model.Invoice, int, error) {
	if perPage <= 0 {
		perPage = 20
	}
	if page <= 0 {
		page = 1
	}

	var total int
	if err := r.db.QueryRow(ctx, `
		SELECT COUNT(*) FROM invoices WHERE tenant_id = $1 AND customer_id = $2
	`, tenantID, customerID).Scan(&total); err != nil {
		return nil, 0, err
	}

	offset := (page - 1) * perPage
	rows, err := r.db.Query(ctx, `
		SELECT id, tenant_id, customer_id, invoice_number, period_month, period_year,
		       package_price, discount, additional_fee, COALESCE(fee_description,''), total_amount,
		       status, due_date, paid_at, paid_amount, payment_method, COALESCE(notes,''),
		       auto_generated, created_at, updated_at
		FROM invoices
		WHERE tenant_id = $1 AND customer_id = $2
		ORDER BY period_year DESC, period_month DESC
		LIMIT $3 OFFSET $4
	`, tenantID, customerID, perPage, offset)
	if err != nil {
		return nil, 0, err
	}
	defer rows.Close()

	var invoices []model.Invoice
	for rows.Next() {
		var inv model.Invoice
		if err := rows.Scan(
			&inv.ID, &inv.TenantID, &inv.CustomerID, &inv.InvoiceNumber,
			&inv.PeriodMonth, &inv.PeriodYear,
			&inv.PackagePrice, &inv.Discount, &inv.AdditionalFee, &inv.FeeDescription, &inv.TotalAmount,
			&inv.Status, &inv.DueDate, &inv.PaidAt, &inv.PaidAmount, &inv.PaymentMethod, &inv.Notes,
			&inv.AutoGenerated, &inv.CreatedAt, &inv.UpdatedAt,
		); err != nil {
			return nil, 0, err
		}
		invoices = append(invoices, inv)
	}
	return invoices, total, rows.Err()
}

func (r *invoiceRepository) ListUnpaidDue(ctx context.Context, tenantID string, dueDate string) ([]model.Invoice, error) {
	rows, err := r.db.Query(ctx, `
		SELECT i.id, i.tenant_id, i.customer_id, i.invoice_number, i.period_month, i.period_year,
		       i.package_price, i.discount, i.additional_fee, COALESCE(i.fee_description,''), i.total_amount,
		       i.status, i.due_date, i.paid_at, i.paid_amount, i.payment_method, COALESCE(i.notes,''),
		       i.auto_generated, i.created_at, i.updated_at,
		       c.name, c.customer_code, COALESCE(c.phone,''), COALESCE(c.address,''),
		       COALESCE(p.name,'')
		FROM invoices i
		JOIN customers c ON c.id = i.customer_id
		LEFT JOIN packages p ON c.package_id = p.id
		WHERE i.tenant_id = $1 AND i.status = 'unpaid' AND i.due_date::date = $2::date
		ORDER BY i.due_date ASC
	`, tenantID, dueDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var invoices []model.Invoice
	for rows.Next() {
		var inv model.Invoice
		var custName, custCode, custPhone, custAddress, pkgName string
		if err := rows.Scan(
			&inv.ID, &inv.TenantID, &inv.CustomerID, &inv.InvoiceNumber, &inv.PeriodMonth, &inv.PeriodYear,
			&inv.PackagePrice, &inv.Discount, &inv.AdditionalFee, &inv.FeeDescription, &inv.TotalAmount,
			&inv.Status, &inv.DueDate, &inv.PaidAt, &inv.PaidAmount, &inv.PaymentMethod, &inv.Notes,
			&inv.AutoGenerated, &inv.CreatedAt, &inv.UpdatedAt,
			&custName, &custCode, &custPhone, &custAddress,
			&pkgName,
		); err != nil {
			return nil, err
		}
		inv.Customer = &model.Customer{ID: inv.CustomerID, Name: custName, CustomerCode: custCode, Phone: custPhone, Address: custAddress}
		if pkgName != "" {
			inv.Customer.Package = &model.Package{Name: pkgName}
		}
		invoices = append(invoices, inv)
	}

	return invoices, nil
}

func (r *invoiceRepository) ListOverdueForIsolir(ctx context.Context, tenantID string, cutoffDate string) ([]model.Invoice, error) {
	rows, err := r.db.Query(ctx, `
		SELECT DISTINCT ON (i.customer_id)
		       i.id, i.tenant_id, i.customer_id, i.invoice_number, i.period_month, i.period_year,
		       i.package_price, i.discount, i.additional_fee, COALESCE(i.fee_description,''), i.total_amount,
		       i.status, i.due_date, i.paid_at, i.paid_amount, i.payment_method, COALESCE(i.notes,''),
		       i.auto_generated, i.created_at, i.updated_at,
		       c.name, c.customer_code, COALESCE(c.phone,''), c.status
		FROM invoices i
		JOIN customers c ON c.id = i.customer_id
		WHERE i.tenant_id = $1 AND i.status = 'unpaid' AND i.due_date::date <= $2::date
		  AND c.status = 'active'
		ORDER BY i.customer_id, i.due_date ASC
	`, tenantID, cutoffDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var invoices []model.Invoice
	for rows.Next() {
		var inv model.Invoice
		var custName, custCode, custPhone, custStatus string
		if err := rows.Scan(
			&inv.ID, &inv.TenantID, &inv.CustomerID, &inv.InvoiceNumber, &inv.PeriodMonth, &inv.PeriodYear,
			&inv.PackagePrice, &inv.Discount, &inv.AdditionalFee, &inv.FeeDescription, &inv.TotalAmount,
			&inv.Status, &inv.DueDate, &inv.PaidAt, &inv.PaidAmount, &inv.PaymentMethod, &inv.Notes,
			&inv.AutoGenerated, &inv.CreatedAt, &inv.UpdatedAt,
			&custName, &custCode, &custPhone, &custStatus,
		); err != nil {
			return nil, err
		}
		inv.Customer = &model.Customer{ID: inv.CustomerID, Name: custName, CustomerCode: custCode, Phone: custPhone, Status: custStatus}
		invoices = append(invoices, inv)
	}

	return invoices, nil
}

func (r *invoiceRepository) CreateBatch(ctx context.Context, invoices []model.Invoice) error {
	if len(invoices) == 0 {
		return nil
	}

	tx, err := r.db.Begin(ctx)
	if err != nil {
		return err
	}
	defer tx.Rollback(ctx)

	for i := range invoices {
		invoices[i].ID = id.New()
		_, err := tx.Exec(ctx, `
			INSERT INTO invoices (
				id, tenant_id, customer_id, invoice_number, period_month, period_year,
				package_price, discount, additional_fee, fee_description, total_amount,
				status, due_date, notes, auto_generated
			) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15)
			ON CONFLICT (tenant_id, customer_id, period_month, period_year) DO NOTHING
		`,
			invoices[i].ID, invoices[i].TenantID, invoices[i].CustomerID, invoices[i].InvoiceNumber,
			invoices[i].PeriodMonth, invoices[i].PeriodYear, invoices[i].PackagePrice, invoices[i].Discount,
			invoices[i].AdditionalFee, invoices[i].FeeDescription, invoices[i].TotalAmount,
			invoices[i].Status, invoices[i].DueDate, invoices[i].Notes, invoices[i].AutoGenerated,
		)
		if err != nil {
			return err
		}
	}

	return tx.Commit(ctx)
}

func (r *invoiceRepository) HasUnpaidInvoice(ctx context.Context, tenantID, customerID string) (bool, error) {
	var exists bool
	err := r.db.QueryRow(ctx, `
		SELECT EXISTS(SELECT 1 FROM invoices WHERE tenant_id = $1 AND customer_id = $2 AND status = 'unpaid')
	`, tenantID, customerID).Scan(&exists)
	return exists, err
}

func (r *invoiceRepository) FindLastPaidInvoice(ctx context.Context, tenantID, customerID string) (*model.Invoice, error) {
	var inv model.Invoice
	err := r.db.QueryRow(ctx, `
		SELECT id, tenant_id, customer_id, invoice_number, period_month, period_year,
		       package_price, discount, additional_fee, COALESCE(fee_description,''), total_amount,
		       status, due_date, paid_at, paid_amount, payment_method, COALESCE(notes,''),
		       auto_generated, created_at, updated_at
		FROM invoices
		WHERE tenant_id = $1 AND customer_id = $2 AND status = 'paid'
		ORDER BY paid_at DESC
		LIMIT 1
	`, tenantID, customerID).Scan(
		&inv.ID, &inv.TenantID, &inv.CustomerID, &inv.InvoiceNumber,
		&inv.PeriodMonth, &inv.PeriodYear,
		&inv.PackagePrice, &inv.Discount, &inv.AdditionalFee, &inv.FeeDescription, &inv.TotalAmount,
		&inv.Status, &inv.DueDate, &inv.PaidAt, &inv.PaidAmount, &inv.PaymentMethod, &inv.Notes,
		&inv.AutoGenerated, &inv.CreatedAt, &inv.UpdatedAt,
	)
	if err != nil {
		if err.Error() == "no rows in result set" {
			return nil, nil
		}
		return nil, err
	}
	return &inv, nil
}

func (r *invoiceRepository) CountPaidInvoices(ctx context.Context, tenantID, customerID string) (int, error) {
	var count int
	err := r.db.QueryRow(ctx,
		`SELECT COUNT(*) FROM invoices WHERE tenant_id = $1 AND customer_id = $2 AND status = 'paid'`,
		tenantID, customerID,
	).Scan(&count)
	return count, err
}
