package model

import "time"

type Invoice struct {
	ID             string     `json:"id"`
	TenantID       string     `json:"tenant_id"`
	CustomerID     string     `json:"customer_id"`
	InvoiceNumber  string     `json:"invoice_number"`
	PeriodMonth    int        `json:"period_month"`
	PeriodYear     int        `json:"period_year"`
	PackagePrice   int64      `json:"package_price"`
	Discount       int64      `json:"discount"`
	AdditionalFee  int64      `json:"additional_fee"`
	FeeDescription string     `json:"fee_description"`
	TotalAmount    int64      `json:"total_amount"`
	Status         string     `json:"status"`
	DueDate        time.Time  `json:"due_date"`
	PaidAt         *time.Time `json:"paid_at,omitempty"`
	PaidAmount     *int64     `json:"paid_amount,omitempty"`
	PaymentMethod  *string    `json:"payment_method,omitempty"`
	Notes          string     `json:"notes"`
	AutoGenerated  bool       `json:"auto_generated"`
	CreatedAt      time.Time  `json:"created_at"`
	UpdatedAt      time.Time  `json:"updated_at"`

	Customer *Customer `json:"customer,omitempty"`
}
