-- migrate:up
ALTER TABLE odps ADD COLUMN IF NOT EXISTS pon_port_id CHAR(26) REFERENCES pon_ports(id) ON DELETE SET NULL;
ALTER TABLE odps ADD COLUMN IF NOT EXISTS sequence SMALLINT DEFAULT 0;
ALTER TABLE odps ADD COLUMN IF NOT EXISTS cable_length_m DECIMAL(10, 2) DEFAULT 0;
ALTER TABLE odps ADD COLUMN IF NOT EXISTS ratio_percent DECIMAL(5, 2) DEFAULT 0;
ALTER TABLE odps ADD COLUMN IF NOT EXISTS splitter_type VARCHAR(20);
ALTER TABLE odps ADD COLUMN IF NOT EXISTS power_level_dbm DECIMAL(8, 2);

CREATE INDEX IF NOT EXISTS idx_odps_pon_port ON odps(pon_port_id);

-- migrate:down
DROP INDEX IF EXISTS idx_odps_pon_port;
ALTER TABLE odps DROP COLUMN IF EXISTS power_level_dbm;
ALTER TABLE odps DROP COLUMN IF EXISTS splitter_type;
ALTER TABLE odps DROP COLUMN IF EXISTS ratio_percent;
ALTER TABLE odps DROP COLUMN IF EXISTS cable_length_m;
ALTER TABLE odps DROP COLUMN IF EXISTS sequence;
ALTER TABLE odps DROP COLUMN IF EXISTS pon_port_id;
